### ISSUE TITLE
Share to FB failed

### ISSUE THREAD

**Issue by ppipee** [KUclap/KUclap#11]
![1606912035323](https://user-images.githubusercontent.com/31619447/100872751-e08d4d80-34d4-11eb-8fc9-766be4b1e48b.jpg)

**Comment by aslupin** [comment]
This message on the development environment or production environment?

**Comment by ppipee** [comment]
this error occurs when shared to fb on prod.

**Comment by aslupin** [comment]
Thank you for reporting this! 😋, This issue occurred because we forgot to switch from development mode to live mode. We created a hotfix for this issue and solve it by adding a Privacy Policy, Terms of Service, and User Data Deletion to the Facebook developer console, then enabled live mode. Now we can share a review as expected. However, I think Facebook will verify all of the URLs that we send to enable live mode soon, so we will monitor them closely 😢. 

I will close this issue. If you found the others please feel free to open the new one or create a Pull Request 😎.
